# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

L1BinomialApproximate <- function(M, C, lambda) {
    .Call(`_l01segmentation_L1BinomialApproximate`, M, C, lambda)
}

L1BinomialApproximateCondensed <- function(M, C, lambda) {
    .Call(`_l01segmentation_L1BinomialApproximateCondensed`, M, C, lambda)
}

blockcoordinatedescent <- function(Yhat, lambda, w, mintimer = 5, tol = 1e-6) {
    .Call(`_l01segmentation_blockcoordinatedescent`, Yhat, lambda, w, mintimer, tol)
}

L0PoissonApproximate <- function(y, l, w) {
    .Call(`_l01segmentation_L0PoissonApproximate`, y, l, w)
}

L0GaussianApproximate <- function(y, l, w) {
    .Call(`_l01segmentation_L0GaussianApproximate`, y, l, w)
}

L0ExponentialApproximate <- function(y, l, w) {
    .Call(`_l01segmentation_L0ExponentialApproximate`, y, l, w)
}

L0BinomialApproximate <- function(y, l, w) {
    .Call(`_l01segmentation_L0BinomialApproximate`, y, l, w)
}

L0PoissonApproximateCondensed <- function(y, l, w) {
    .Call(`_l01segmentation_L0PoissonApproximateCondensed`, y, l, w)
}

L0GaussianApproximateCondensed <- function(y, l, w) {
    .Call(`_l01segmentation_L0GaussianApproximateCondensed`, y, l, w)
}

L0ExponentialApproximateCondensed <- function(y, l, w) {
    .Call(`_l01segmentation_L0ExponentialApproximateCondensed`, y, l, w)
}

L0BinomialApproximateCondensed <- function(y, l, w) {
    .Call(`_l01segmentation_L0BinomialApproximateCondensed`, y, l, w)
}

L0PoissonApproximateN <- function(y, N, w) {
    .Call(`_l01segmentation_L0PoissonApproximateN`, y, N, w)
}

L0GaussianApproximateN <- function(y, N, w) {
    .Call(`_l01segmentation_L0GaussianApproximateN`, y, N, w)
}

L0ExponentialApproximateN <- function(y, N, w) {
    .Call(`_l01segmentation_L0ExponentialApproximateN`, y, N, w)
}

L0BinomialApproximateN <- function(y, N, w) {
    .Call(`_l01segmentation_L0BinomialApproximateN`, y, N, w)
}

L0PoissonApproximateNCondensed <- function(y, N, w) {
    .Call(`_l01segmentation_L0PoissonApproximateNCondensed`, y, N, w)
}

L0GaussianApproximateNCondensed <- function(y, N, w) {
    .Call(`_l01segmentation_L0GaussianApproximateNCondensed`, y, N, w)
}

L0ExponentialApproximateNCondensed <- function(y, N, w) {
    .Call(`_l01segmentation_L0ExponentialApproximateNCondensed`, y, N, w)
}

L0BinomialApproximateNCondensed <- function(y, N, w) {
    .Call(`_l01segmentation_L0BinomialApproximateNCondensed`, y, N, w)
}

L0PoissonBreakPoint <- function(y, w) {
    .Call(`_l01segmentation_L0PoissonBreakPoint`, y, w)
}

L0GaussianBreakPoint <- function(y, w) {
    .Call(`_l01segmentation_L0GaussianBreakPoint`, y, w)
}

L0ExponentialBreakPoint <- function(y, w) {
    .Call(`_l01segmentation_L0ExponentialBreakPoint`, y, w)
}

L0BinomialBreakPoint <- function(y, w) {
    .Call(`_l01segmentation_L0BinomialBreakPoint`, y, w)
}

L1PoissonApproximate <- function(y, w, lambda) {
    .Call(`_l01segmentation_L1PoissonApproximate`, y, w, lambda)
}

L1PoissonApproximateCondensed <- function(y, w, lambda) {
    .Call(`_l01segmentation_L1PoissonApproximateCondensed`, y, w, lambda)
}

L1GaussianApproximate <- function(y, l2, weights = NULL) {
    .Call(`_l01segmentation_L1GaussianApproximate`, y, l2, weights)
}

L1GaussianApproximateCondensed <- function(y, l2, w = NULL) {
    .Call(`_l01segmentation_L1GaussianApproximateCondensed`, y, l2, w)
}

