# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Xhat <- function(w) {
    .Call(`_l01segmentation_Xhat`, w)
}

dotX <- function(R, w) {
    .Call(`_l01segmentation_dotX`, R, w)
}

dotXT <- function(R, w) {
    .Call(`_l01segmentation_dotXT`, R, w)
}

rowXhatnorm <- function(i, w, n) {
    .Call(`_l01segmentation_rowXhatnorm`, i, w, n)
}

blockcoordinatedescent <- function(Yhat, lambda, w) {
    .Call(`_l01segmentation_blockcoordinatedescent`, Yhat, lambda, w)
}

L0PoisErrSeg <- function(y, l2, w = NULL, max_seg_length = 3000L, average_range_length = 4L) {
    .Call(`_l01segmentation_L0PoisErrSeg`, y, l2, w, max_seg_length, average_range_length)
}

L0SqrtErrSeg <- function(y, l2, w = NULL, max_seg_length = 3000L, average_range_length = 4L) {
    .Call(`_l01segmentation_L0SqrtErrSeg`, y, l2, w, max_seg_length, average_range_length)
}

L0SqrtErrBreakPoints <- function(y, l2, w = NULL, max_seg_length = 3000L, average_range_length = 4L) {
    .Call(`_l01segmentation_L0SqrtErrBreakPoints`, y, l2, w, max_seg_length, average_range_length)
}

L1SqrtErrFil <- function(y, l2, weights = NULL) {
    .Call(`_l01segmentation_L1SqrtErrFil`, y, l2, weights)
}

